ALTER TABLE animal
    ADD COLUMN tipo VARCHAR(20) NOT NULL,
    ADD COLUMN idade VARCHAR(20) NOT NULL,
    ADD COLUMN castrado BOOLEAN NOT NULL,
    ADD COLUMN vermifugado BOOLEAN NOT NULL,
    ADD COLUMN srd BOOLEAN NOT NULL,
    ADD COLUMN descricao TEXT,
    ADD COLUMN created_at TIMESTAMP NOT NULL,
    ADD COLUMN updated_at TIMESTAMP NOT NULL;